AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Starter Kit - Lambda API Backend

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  UsersApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/apps/api/
      Handler: get-users.handler
      Description: Get all users
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users
            Method: GET

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/apps/api/
      Handler: get-user.handler
      Description: Get user by ID
      Events:
        GetUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users/{id}
            Method: GET

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/apps/api/
      Handler: create-user.handler
      Description: Create a new user
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users
            Method: POST

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/apps/api/
      Handler: update-user.handler
      Description: Update user
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users/{id}
            Method: PUT

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/apps/api/
      Handler: delete-user.handler
      Description: Delete user
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApi
            Path: /users/{id}
            Method: DELETE

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${UsersApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  
  GetUsersFunctionArn:
    Description: Get Users Lambda Function ARN
    Value: !GetAtt GetUsersFunction.Arn
  
  GetUserFunctionArn:
    Description: Get User Lambda Function ARN
    Value: !GetAtt GetUserFunction.Arn
  
  CreateUserFunctionArn:
    Description: Create User Lambda Function ARN
    Value: !GetAtt CreateUserFunction.Arn
  
  UpdateUserFunctionArn:
    Description: Update User Lambda Function ARN
    Value: !GetAtt UpdateUserFunction.Arn
  
  DeleteUserFunctionArn:
    Description: Delete User Lambda Function ARN
    Value: !GetAtt DeleteUserFunction.Arn

